import {
	Student,
	CourseAnalytics,
	DashboardMetrics,
	ChartData,
	SkillAnalytics,
	SkillScores,
} from "@/types";

export const dashboardMetrics: DashboardMetrics = {
	totalStudents: 1247,
	totalStudentsChange: 8.3,
	activeAssessments: 342,
	activeAssessmentsChange: 15.7,
	completedAssessments: 905,
	completedAssessmentsChange: 23.1,
	averageOverallScore: 78.4,
	averageOverallScoreChange: 4.2,
	placementRecommendationRate: 72.8,
	placementRecommendationRateChange: 6.9,
};

export const skillAnalytics: SkillAnalytics[] = [
	{
		skill: "Domain/Technical Skills",
		averageScore: 82.3,
		totalAssessments: 905,
		improvementTrend: 5.2,
	},
	{
		skill: "Communication Skills",
		averageScore: 76.8,
		totalAssessments: 905,
		improvementTrend: 3.1,
	},
	{
		skill: "Digital Skills",
		averageScore: 84.1,
		totalAssessments: 905,
		improvementTrend: 7.8,
	},
	{
		skill: "Interpersonal Skills",
		averageScore: 73.5,
		totalAssessments: 905,
		improvementTrend: 2.4,
	},
	{
		skill: "Creativity",
		averageScore: 79.2,
		totalAssessments: 905,
		improvementTrend: 4.6,
	},
];

export const chartData: ChartData[] = [
	{
		date: "Jan",
		overallScore: 75,
		domainSkills: 78,
		communicationSkills: 72,
		digitalSkills: 80,
		interpersonalSkills: 70,
		creativitySkills: 76,
	},
	{
		date: "Feb",
		overallScore: 76,
		domainSkills: 79,
		communicationSkills: 73,
		digitalSkills: 81,
		interpersonalSkills: 71,
		creativitySkills: 77,
	},
	{
		date: "Mar",
		overallScore: 74,
		domainSkills: 77,
		communicationSkills: 71,
		digitalSkills: 79,
		interpersonalSkills: 69,
		creativitySkills: 75,
	},
	{
		date: "Apr",
		overallScore: 78,
		domainSkills: 81,
		communicationSkills: 75,
		digitalSkills: 83,
		interpersonalSkills: 73,
		creativitySkills: 79,
	},
	{
		date: "May",
		overallScore: 79,
		domainSkills: 82,
		communicationSkills: 76,
		digitalSkills: 84,
		interpersonalSkills: 74,
		creativitySkills: 80,
	},
	{
		date: "Jun",
		overallScore: 77,
		domainSkills: 80,
		communicationSkills: 74,
		digitalSkills: 82,
		interpersonalSkills: 72,
		creativitySkills: 78,
	},
	{
		date: "Jul",
		overallScore: 80,
		domainSkills: 83,
		communicationSkills: 77,
		digitalSkills: 85,
		interpersonalSkills: 75,
		creativitySkills: 81,
	},
	{
		date: "Aug",
		overallScore: 78,
		domainSkills: 81,
		communicationSkills: 75,
		digitalSkills: 83,
		interpersonalSkills: 73,
		creativitySkills: 79,
	},
];

export const students: Student[] = [
	{
		_id: "1",
		studentId: "AGI001",
		rollNumber: "MBA2024001",
		email: "priya.sharma@agi.edu.in",
		firstName: "Priya",
		lastName: "Sharma",
		fullName: "Priya Sharma",
		course: "MBA",
		division: "A",
		phone: "+91 9876543210",
		yearOfStudy: 1,
		specialization: "Marketing",
		status: "active",
		isFirstLogin: false,
		lastLoginAt: new Date("2025-08-29T10:30:00Z"),
		createdAt: new Date("2025-01-15T09:00:00Z"),
		updatedAt: new Date("2025-08-29T10:30:00Z"),
		latestAssessment: {
			_id: "assess1",
			studentId: "AGI001",
			skillScores: {
				domainSkills: 85,
				communicationSkills: 78,
				digitalSkills: 82,
				interpersonalSkills: 80,
				creativitySkills: 77,
			},
			overallScore: 80.4,
			placementRecommended: true,
			assessmentDate: new Date("2025-08-25T14:00:00Z"),
			completionStatus: "completed",
			timeSpent: 45,
			answers: [],
		},
	},
	{
		_id: "2",
		studentId: "AGI002",
		rollNumber: "MCA2024002",
		email: "rahul.kumar@agi.edu.in",
		firstName: "Rahul",
		lastName: "Kumar",
		fullName: "Rahul Kumar",
		course: "MCA",
		division: "B",
		phone: "+91 9876543211",
		yearOfStudy: 2,
		specialization: "Software Development",
		status: "active",
		isFirstLogin: false,
		lastLoginAt: new Date("2025-08-28T16:45:00Z"),
		createdAt: new Date("2025-01-18T09:00:00Z"),
		updatedAt: new Date("2025-08-28T16:45:00Z"),
		latestAssessment: {
			_id: "assess2",
			studentId: "AGI002",
			skillScores: {
				domainSkills: 92,
				communicationSkills: 74,
				digitalSkills: 89,
				interpersonalSkills: 76,
				creativitySkills: 81,
			},
			overallScore: 82.4,
			placementRecommended: true,
			assessmentDate: new Date("2025-08-27T11:30:00Z"),
			completionStatus: "completed",
			timeSpent: 52,
			answers: [],
		},
	},
	{
		_id: "3",
		studentId: "AGI003",
		rollNumber: "PGDM2024003",
		email: "sneha.patel@agi.edu.in",
		firstName: "Sneha",
		lastName: "Patel",
		fullName: "Sneha Patel",
		course: "PGDM",
		division: "A",
		phone: "+91 9876543212",
		yearOfStudy: 1,
		specialization: "Finance",
		status: "active",
		isFirstLogin: true,
		createdAt: new Date("2025-08-20T09:00:00Z"),
		updatedAt: new Date("2025-08-20T09:00:00Z"),
	},
	{
		_id: "4",
		studentId: "AGI004",
		rollNumber: "BMS2024004",
		email: "arjun.singh@agi.edu.in",
		firstName: "Arjun",
		lastName: "Singh",
		fullName: "Arjun Singh",
		course: "BMS",
		division: "C",
		phone: "+91 9876543213",
		yearOfStudy: 3,
		status: "active",
		isFirstLogin: false,
		lastLoginAt: new Date("2025-08-29T09:15:00Z"),
		createdAt: new Date("2024-07-10T09:00:00Z"),
		updatedAt: new Date("2025-08-29T09:15:00Z"),
		latestAssessment: {
			_id: "assess4",
			studentId: "AGI004",
			skillScores: {
				domainSkills: 78,
				communicationSkills: 82,
				digitalSkills: 75,
				interpersonalSkills: 85,
				creativitySkills: 80,
			},
			overallScore: 80.0,
			placementRecommended: true,
			assessmentDate: new Date("2025-08-26T13:20:00Z"),
			completionStatus: "completed",
			timeSpent: 38,
			answers: [],
		},
	},
	{
		_id: "5",
		studentId: "AGI005",
		rollNumber: "BARCH2024005",
		email: "maya.reddy@agi.edu.in",
		firstName: "Maya",
		lastName: "Reddy",
		fullName: "Maya Reddy",
		course: "B.Arch.",
		division: "A",
		phone: "+91 9876543214",
		yearOfStudy: 4,
		specialization: "Sustainable Architecture",
		status: "active",
		isFirstLogin: false,
		lastLoginAt: new Date("2025-08-29T11:00:00Z"),
		createdAt: new Date("2021-08-15T09:00:00Z"),
		updatedAt: new Date("2025-08-29T11:00:00Z"),
		latestAssessment: {
			_id: "assess5",
			studentId: "AGI005",
			skillScores: {
				domainSkills: 88,
				communicationSkills: 79,
				digitalSkills: 86,
				interpersonalSkills: 83,
				creativitySkills: 91,
			},
			overallScore: 85.4,
			placementRecommended: true,
			assessmentDate: new Date("2025-08-24T15:45:00Z"),
			completionStatus: "completed",
			timeSpent: 41,
			answers: [],
		},
	},
];

export const courseAnalytics: CourseAnalytics[] = [
	{
		course: "MBA",
		totalStudents: 156,
		averageScore: 79.3,
		placementRate: 84.6,
		topPerformers: 23,
	},
	{
		course: "MCA",
		totalStudents: 89,
		averageScore: 82.1,
		placementRate: 91.0,
		topPerformers: 18,
	},
	{
		course: "PGDM",
		totalStudents: 134,
		averageScore: 77.8,
		placementRate: 78.4,
		topPerformers: 19,
	},
	{
		course: "BMS",
		totalStudents: 201,
		averageScore: 76.2,
		placementRate: 72.1,
		topPerformers: 28,
	},
	{
		course: "B.Arch.",
		totalStudents: 67,
		averageScore: 81.5,
		placementRate: 89.6,
		topPerformers: 12,
	},
];

// Sample assessment questions
export const sampleQuestions = [
	{
		_id: "q1",
		questionText:
			"Which of the following is the most effective approach to stakeholder communication in a project?",
		options: [
			"Send regular email updates to all stakeholders",
			"Hold weekly meetings with all stakeholders",
			"Tailor communication based on stakeholder needs and preferences",
			"Use only formal documentation for communication",
		],
		correctAnswer:
			"Tailor communication based on stakeholder needs and preferences",
		skillCategory: "communicationSkills" as keyof SkillScores,
		difficulty: "medium" as const,
		points: 10,
	},
	{
		_id: "q2",
		questionText:
			"In digital transformation, what is the primary benefit of cloud computing?",
		options: [
			"Reduced hardware costs only",
			"Improved scalability and accessibility",
			"Better security by default",
			"Elimination of IT staff needs",
		],
		correctAnswer: "Improved scalability and accessibility",
		skillCategory: "digitalSkills" as keyof SkillScores,
		difficulty: "medium" as const,
		points: 10,
	},
];
